name: Generate libraries report
on:
  schedule:
    - cron:  '0 */1 * * *' #TODO
  push:
    branches:
      - '*'
jobs:
  github-repo-tools:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      - run: npm ci
      - run: npx ts-node src/tasks/generateReports.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_LOGIN: MiguelSavignano #TODO

      - uses: stefanzweifel/git-auto-commit-action@v4.1.1
        with:
          commit_message: Apply automatic changes
